### ISSUE TITLE
Pesquisar tecnologias

### ISSUE THREAD

**Issue by Victor-oss** [fga-eps-mds/2022-2-Squad08#10]
# Descrição
A partir do tema proposto, pesquisar tecnologias necessárias para o desenvolvimento do software.

# Tarefas
- [x] Pesquisar tecnologias que possam ser usadas no projeto.

# Critérios de Aceitação
- [x] Documento com as propostas de tecnologia aprovado pela equipe e disponibilizado no github.

**Comment by daniel-de-sousa** [comment]
# Tecnologias

Em anexo segue o docuemento com as tecnologias consideradas relevantes para a execução do projeto.

[Tecnologias.docx](https://github.com/fga-eps-mds/2022-2-Squad08/files/9990220/Tecnologias.docx)
