### ISSUE TITLE
Consumir dados de uma tabela

### ISSUE THREAD

**Issue by Victor-oss** [fga-eps-mds/2022-2-Squad08#13]
# Descrição
Fazer um código que receba um endereço de um arquivo com uma tabela e em seguida consuma os dados

# Tarefas

- [x] Criar tabela de exemplo
- [x] Fazer código que leia os registros da tabela usando pandas

# Critérios de Aceitação
- [x] Branch com o código que consome registros de uma tabela e imprime no terminal aprovada pelo grupo

**Comment by phmelosilva** [comment]
Foi finalizado e testado o consumo de dados de uma tabela excel

**Comment by PedroSampaioDias** [comment]
Eu e o @phmelosilva implementamos um exemplo de consumo de uma tabela *.xlsx
