### ISSUE TITLE
Pesquisar tecnologias de conversão de HTML para PDF

### ISSUE THREAD

**Issue by Victor-oss** [fga-eps-mds/2022-2-Squad08#36]
# Descrição
Pesquisar tecnologias para fazer a conversão do template de certificado em HTML para PDF.

# Tarefas
- [x] Pesquisar tecnologias
- [x] Fazer spike que faz a conversão do template de certificado em HTML para PDF

# Critérios de Aceitação
- [x] Arquivo com descrição das tecnologias de conversão
- [x] Branch com spike que faz a conversão do template do certificado em HTML para PDF

**Comment by Leanddro13** [comment]
pdfkit documentation: https://pypi.org/project/pdfkit/

wkhtmltopdf documentation: https://wkhtmltopdf.org/usage/wkhtmltopdf.txt
