### ISSUE TITLE
Corrigir erro no docker

### ISSUE THREAD

**Issue by Victor-oss** [fga-eps-mds/2022-2-Squad08#43]
# Descrição
Configurar o docker para instalar o wkhtmltopdf e rodar aplicação

# Tarefas

- [ ] Colocar wkhtmltopdf como requisito  
- [ ] Rodar a aplicação no docker

# Critérios de Aceitação
- [ ] Branch com o docker funcionando aprovada pelo grupo

**Comment by PedroSampaioDias** [comment]
A tecnologia docker vai ser abandonada. 
Inicialmente, escolhemos o docker, pois tínhamos percebido uma falsa semelhança entre o contêiner e gerenciadores de pacote e dependências como o Poetry. Percebemos a diferença de uso e em grupo decidimos trocar a tecnologia. 
Estamos decidindo qual ferramenta gerenciadora de pacote e dependências será utilizada.
