### ISSUE TITLE
Atualizar README 

### ISSUE THREAD

**Issue by Victor-oss** [fga-eps-mds/2022-2-Squad08#44]
# Descrição
Fazer as alterações no README para a Release 1

# Tarefas
- [x] Colocar alterações pedidas pela professora no README como bugs reportados

# Critérios de Aceitação
- [x] Branch com alterações no README aprovada pelo grupo

**Comment by phmelosilva** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Grupo-8---Certiflow-637642f781e2a2d03fa1c854/issues/fga-eps-mds/2022-2-Certifik8/44?planning-poker) with Zenhub @Leanddro13 @Victor-oss @PedroSampaioDias @BlimblimCFT
