### ISSUE TITLE
Refatorar Código

### ISSUE THREAD

**Issue by Victor-oss** [fga-eps-mds/2022-2-Squad08#57]
# Descrição
Aperfeiçoar código seguindo diretrizes de clean code, princípios de orientação a objetos e tratamento de erros

# Tarefas
- [x] Diminuir a responsabilidades de alguns métodos
- [x] Tratar possíveis erros do usuário
- [x] Aperfeiçoar sintaxe do código com Flake8

# Critérios de Aceitação
- [x] Branch com as alterações pedidas aprovada pelo grupo

**Comment by PedroSampaioDias** [comment]
@Victor-oss dá uma olhada nesse post do reddit: [Link](https://www.reddit.com/r/Python/comments/82hgzm/any_advantages_of_flake8_over_pylint/)
Talvez a gente possa utilizar o flake8 e o pylint.
