### ISSUE TITLE
Adicionar scripts no git actions

### ISSUE THREAD

**Issue by Victor-oss** [fga-eps-mds/2022-2-Squad08#61]
# Descrição
Adicionar mais scripts no git actions

# Tarefa
- [x] Script para rodar testes e verificar o nível de clean code do código em commits e pull requests
- [x] Script para fazer o deploy no Pypi

# Critérios de Aceitação
- [x] Scripts com as alterações aprovados pelo grupo

**Comment by Leanddro13** [comment]
Código revisado
