### ISSUE TITLE
Resolver os conflitos de mesclagem

### ISSUE THREAD

**Issue by PedroSampaioDias** [fga-eps-mds/2022-2-Squad08#62]
# Descrição
Resolver os conflitos de mesclagem do pull request (#56)

# Tarefas

- [x] Conflito na "certificado.py"
- [x] Conflito na "main.py"
- [x] Criar no mínimo dois exemplos com a nova coluna "Informações"

# Critérios de Aceitação

- [x] Todos os conflitos foram corrigidos
- [x] O funcionamento esperado foi mantido
- [x] Testada pelo **Assignee**

# Informações Adicionais
PR relacionados: (#56) e (#55)

**Comment by Leanddro13** [comment]
Código testado e aprovado
