### ISSUE TITLE
Procurar e implementar biblioteca para substituir o Tkinter

### ISSUE THREAD

**Issue by Victor-oss** [fga-eps-mds/2022-2-Squad08#67]
# Descrição
Devido ao fato do visual da janela aberta pelo Tkinter para procurar os arquivos dos certificados ser ruim, precisamos de uma nova biblioteca que apresente um visual melhor para buscar os arquivos

# Tarefas

- [x] Procurar biblioteca que abra uma janela do gerenciador de arquivos
- [x] Implementar a biblioteca encontrada no código

# Critérios de Aceitação
- [x] Branch com as alterações pedidas aprovadas pelo time

**Comment by PedroSampaioDias** [comment]
Optamos pelo Zenity para implementar um dialogfile na aplicação devido à sua facilidade de uso e disponibilidade em muitas distros Linux. Preparamos os arquivos para criar testes unitários e lidar com possíveis erros.

@BlimblimCFT @phmelosilva
