### ISSUE TITLE
Adicionar feature de escolha da localização das pastas dos certificados

### ISSUE THREAD

**Issue by Victor-oss** [fga-eps-mds/2022-2-Squad08#68]
# Descrição
Atualmente, depois que os certificados são gerados, eles são armazenados em pastas dentro da pasta Downloads. Precisamos permitir ao próprio usuário escolher onde deseja armazenar as pastas

# Tarefas
- [x] Adicionar funcionalidade de escolha da pasta na aplicação

# Critérios de Aceitação
- [x] Branch com as alterações pedidas aprovadas pelo grupo

**Comment by PedroSampaioDias** [comment]
Criamos uma classe no arquivo [folder_selectior.py](https://github.com/fga-eps-mds/2022-2-Certifik8/blob/67-nova-interface/Certifik8/modules/selection/folder_selection.py) que fornece uma solução fácil e eficiente para selecionar um diretório através de um filedialog. Essa classe pode ser útil para a implementação desta issue e retorna somente o caminho selecionado. Espero que  esse código ajude na resolução desta tarefa.

@BlimblimCFT @phmelosilva
