### ISSUE TITLE
Pesquisar Arquitetura

### ISSUE THREAD

**Issue by Victor-oss** [fga-eps-mds/2022-2-Squad08#8]
# Descrição
A partir do tema proposto, fazer proposta de arquitetura para o projeto.

# Tarefas

- [x] Pesquisar arquiteturas
- [x] Procurar projetos parecidos

# Critérios de Aceitação

- [x] Documento com propostas de arquiteturas aprovado pelo grupo e disponíveis no git

**Comment by Victor-oss** [comment]
Documento com pesquisa sobre arquitetura: https://docs.google.com/document/d/14EKyXmVpoqTxW1bSQABttjgki0_mIySPxyWOGMrHNmU/edit?usp=sharing

**Comment by PedroSampaioDias** [comment]
Resumo sobre arquitetura a ferramentas: [Notion - Resumo Arquitetura](https://carnelian-legal-e2b.notion.site/Arquitetura-Certificados-0b51714fdb784517a5133d1746b41c81)
