### ISSUE TITLE
Backlog e levantamento dos épicos/features

### ISSUE THREAD

**Issue by Victor-oss** [fga-eps-mds/2022-2-Squad08#9]
# Descrição 
A partir da proposta, fazer propostas de backlog e de épicos/features necessários para o software. 

# Tarefas
- [x] Fazer o backlog do software
- [x] Fazer levantamento dos épicos/features do software

# Criterios de Aceitação
- [x] Backlog e os épicos/features aprovados pela equipe e disponíveis no github

**Comment by Leanddro13** [comment]
Boa noite, foi realizado o Backlog da nossa aplicação, segue o link:
https://docs.google.com/spreadsheets/d/1cHnC-sz8Q3FXaWVZfTfTw7nndV3WExw0K1l8FmCQ850/edit?usp=sharing
